INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'CDETALLE', N'Cabecera Detalle', NULL, 1, N'Forms/Ejemplo/CabeceraDetalle.aspx', N'S', 93, N'A', N'ADMIN', CAST(0x0000A60A008DD2C4 AS DateTime), NULL, CAST(0x0000A60A0119F67E AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'DASHBOAR', N'DashBoard', NULL, 4, N'Forms/Ejemplo/DashBoard.aspx', N'S', 95, N'A', N'SYSTEM', CAST(0x0000A60A00FF4CE3 AS DateTime), NULL, CAST(0x0000A60A0119F681 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'DRAGDROP', N'Drag and Drop', NULL, 5, N'Forms/Ejemplo/DragAndDrop.aspx', N'S', 94, N'A', N'SYSTEM', CAST(0x0000A60A00FF1207 AS DateTime), NULL, CAST(0x0000A60A0119F682 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'EXPORTAR', N'Exportar Documento', NULL, 6, N'Forms/Ejemplo/Exportar.aspx', N'S', 59, N'A', N'ADMIN', CAST(0x0000A5D200B1850D AS DateTime), NULL, CAST(0x0000A60A0119F682 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'FILEINPU', N'Subida de Archivos', NULL, 8, N'Forms/Ejemplo/FileInput.aspx', N'S', 62, N'A', N'ADMIN', CAST(0x0000A5D2010138CE AS DateTime), NULL, CAST(0x0000A60A0119F684 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'FORM    ', N'Controles de Formulario', NULL, 2, N'Forms/Ejemplo/Formulario.aspx', N'S', 60, N'A', N'ADMIN', CAST(0x0000A5D200CA3DDA AS DateTime), NULL, CAST(0x0000A60A0119F67F AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'MASCARA ', N'Controles de Mascara', NULL, 3, N'Forms/Ejemplo/Mascara.aspx', N'S', 61, N'A', N'ADMIN', CAST(0x0000A5D200FCF80D AS DateTime), NULL, CAST(0x0000A60A0119F680 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'EJEMPLO ', N'USERCONT', N'User Control', NULL, 7, N'Forms/Ejemplo/UserControl.aspx', N'S', 96, N'A', N'SYSTEM', CAST(0x0000A60A00FF700D AS DateTime), NULL, CAST(0x0000A60A0119F683 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'HOME    ', N'CAMBCON ', N'Cambiar Contraseña', NULL, 1, N'Forms/Seguridad/CambiarContrasenia.aspx', N'S', 1, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011DC10A AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'HOME    ', N'CONTRASE', N'Contraseña', NULL, 2, N'Forms/Seguridad/Contrasenia.aspx', N'N', 2, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011DC16F AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'HOME    ', N'DASHBOAR', N'Dashboard', NULL, 3, N'Index.aspx', N'S', 72, N'A', N'ADMIN', CAST(0x0000A5E5016BE83F AS DateTime), NULL, CAST(0x0000A5FA011DC1D4 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'HOME    ', N'INICIO  ', N'Módulo', NULL, 4, N'Modulo.aspx', N'S', 3, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011DC239 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'HOME    ', N'PERFUSU ', N'Perfil del usuario', NULL, 5, N'Forms/Seguridad/PerfilUsuario.aspx', N'S', 4, N'A', N'ADMIN', CAST(0x0000A4E600FC2584 AS DateTime), NULL, CAST(0x0000A5FA011DC29E AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'ACTPERS ', N'Persona', NULL, 7, N'Forms/Seguridad/Persona.aspx', N'S', 16, N'A', N'ADMIN', CAST(0x0000A4EF0100795E AS DateTime), NULL, CAST(0x0000A5FA011E9AF5 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'ALMACEN ', N'Almacen de Documentos', NULL, 1, N'Forms/Seguridad/Almacen.aspx', N'S', 17, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011E988D AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'DISPOSIT', N'Dispositivo', NULL, 2, N'Forms/Seguridad/Dispositivo.aspx', N'S', 18, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011E98F3 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'EMPLEADO', N'Empleado', NULL, 6, N'Forms/Seguridad/Empleado.aspx', N'S', 19, N'I', N'ADMIN', NULL, N'SYSTEM', CAST(0x0000A5F6014721AE AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'MENU    ', N'Menu', NULL, 3, N'Forms/Seguridad/Menu.aspx', N'S', 20, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011E9958 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'MODULO  ', N'Módulos', NULL, 4, N'Forms/Seguridad/Modulo.aspx', N'S', 73, N'A', N'ADMIN', CAST(0x0000A5E8012AB6B4 AS DateTime), NULL, CAST(0x0000A5FA011E99BC AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'PARAMETR', N'Parámetros', NULL, 5, N'Forms/Seguridad/Parametro.aspx', N'S', 21, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011E9A20 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'PERFIL  ', N'Perfil', NULL, 6, N'Forms/Seguridad/Perfil.aspx', N'S', 22, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011E9A84 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGALMAC', N'Registro Almacen de documentos', N'ALMACEN ', 4, N'Forms/Seguridad/RegistroAlmacen.aspx', N'N', 23, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5CA0156751B AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGDISP ', N'Registro Dispositivo', N'DISPOSIT', 6, N'Forms/Seguridad/RegistroDispositivo.aspx', N'N', 24, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5CA01567611 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGEMPLE', N'Registrar Empleado', N'EMPLEADO', 8, N'Forms/Seguridad/RegistroEmpleado.aspx', N'N', 25, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5CA0153D604 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGMODUL', N'Registrar Módulo', N'MODULO  ', 0, N'Forms/Seguridad/RegistroModulo.aspx', N'N', 74, N'A', N'ADMIN', CAST(0x0000A5E8012AE3F6 AS DateTime), N'ADMIN', CAST(0x0000A5E8012AE3F6 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGPARAM', N'Registro Parametro', N'PARAMETR', 2, N'Forms/Seguridad/RegistroParametro.aspx', N'N', 26, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5CA0156744A AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGPERFI', N'Registro Perfil', N'PERFIL  ', 13, N'Forms/Seguridad/RegistroPerfil.aspx', N'N', 27, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5CA0153D81E AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGPERS ', N'Registrar Persona', N'ACTPERS ', 3, N'Forms/Seguridad/RegistroPersona.aspx', N'N', 28, N'A', N'ADMIN', CAST(0x0000A4EF0100D54C AS DateTime), NULL, CAST(0x0000A5CA0153D3F7 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'REGUSUAR', N'Registro Usuario', N'USUARIO ', 15, N'Forms/Seguridad/RegistroUsuario.aspx', N'N', 29, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5CA0153D8ED AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'RETIPDOC', N'Registro de Tipo de Documento', N'TIPODOCU', 0, N'Forms/Seguridad/RegistroTipoDocumento.aspx', N'N', 79, N'A', N'ADMIN', CAST(0x0000A5F600F24120 AS DateTime), N'ADMIN', CAST(0x0000A5F600F24120 AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'TIPODOCU', N'Tipo de Documento', NULL, 8, N'Forms/Seguridad/TipoDocumento.aspx', N'S', 78, N'A', N'ADMIN', CAST(0x0000A5F600F1E764 AS DateTime), NULL, CAST(0x0000A5FA011E9B5A AS DateTime))
GO
INSERT [SecurityGrupoDetalle] ([IdModulo], [IdGrupo], [IdDetalle], [Descripcion], [IdDetallePadre], [Orden], [URL], [FlagVisible], [IdImagen], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioModificacion], [FechaModificacion]) VALUES (N'CORE    ', N'SECURITY', N'USUARIO ', N'Usuario', NULL, 9, N'Forms/Seguridad/Usuario.aspx', N'S', 30, N'A', N'ADMIN', NULL, NULL, CAST(0x0000A5FA011E9BBD AS DateTime))
GO